# Generated by Django 2.2.5 on 2019-09-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('year', models.CharField(choices=[('F', 'Freshman'), ('S', 'Sophomore'), ('J', 'Junior'), ('N', 'Senior'), ('G', 'Grad Student')], max_length=1)),
                ('cleanliness', models.CharField(choices=[('C', 'Clean'), ('I', 'Intermediate'), ('M', 'Messy')], max_length=1)),
                ('smoking', models.BooleanField()),
                ('looking_for_gender', models.BooleanField(null=True)),
                ('price_floor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_ceiling', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
