# Generated by Django 2.2.5 on 2019-09-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('num_rooms', models.IntegerField()),
                ('num_bath', models.DecimalField(decimal_places=1, max_digits=3)),
                ('num_kitchen', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.TextField()),
            ],
        ),
    ]
