# Generated by Django 2.2.5 on 2019-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateapplication',
            name='name',
            field=models.CharField(default='Fake name', max_length=30),
            preserve_default=False,
        ),
    ]
