# Generated by Django 2.2.5 on 2019-10-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roommateapplication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommateapplication',
            name='looking_for_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
